import {
  SiReact,
  SiNextdotjs,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiJsonwebtokens,
  SiPostgresql,
  SiSupabase,
  SiPrisma,
  SiGit,
  SiGithub,
  SiPostman,
  SiJira,
  SiPython,
  SiOpenjdk,
} from "react-icons/si";
import {
  TbApi,
  TbDatabase,
  TbChartBar,
  TbSparkles,
  TbServer,
  TbTestPipe,
  TbTopologyStar3,
  TbCode,
  TbRocket,
  TbRoute,
} from "react-icons/tb";

export const iconMap = {
  react: SiReact,
  next: SiNextdotjs,
  js: SiJavascript,
  ts: SiTypescript,
  html: SiHtml5,
  css: SiCss3,
  tailwind: SiTailwindcss,
  node: SiNodedotjs,
  express: SiExpress,
  jwt: SiJsonwebtokens,
  postgres: SiPostgresql,
  supabase: SiSupabase,
  prisma: SiPrisma,
  git: SiGit,
  github: SiGithub,
  postman: SiPostman,
  jira: SiJira,
  python: SiPython,
  java: SiOpenjdk,
  api: TbApi,
  database: TbDatabase,
  chart: TbChartBar,
  ai: TbSparkles,
  automation: TbRoute,
  server: TbServer,
  test: TbTestPipe,
  system: TbTopologyStar3,
  code: TbCode,
  rocket: TbRocket,
};
